<?php

namespace My\JobeetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PosteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosteRepository extends EntityRepository
{
}
