services:
    sonata.admin.post:
        class: My\JobeetBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Job" }
        arguments:
            - ~
            - My\JobeetBundle\Entity\Job
            - ~
        calls:
            - [ setTranslationDomain, [JobeetBundle]]