My\JobeetBundle\Entity\Document:
    type: entity
    table: document
    repositoryClass: My\JobeetBundle\Repository\DocumentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        path:
            type: string
            length: 255
    oneToMany:
        posts:
            targetEntity: Poste
            mappedBy: document
    lifecycleCallbacks:
      prePersist: [ preUpload,upload ]
      preUpdate:  [ preUpload,upload ]
      postRemove: [ removeUpload ]
