My\JobeetBundle\Entity\Poste:
    type: entity
    table: poste
    repositoryClass: My\JobeetBundle\Repository\PosteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        lettreM:
            type: text
    manyToOne:
        document:
          targetEntity: Document
          inversedBy: posts
          joinColumn:
            name: document_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
