My\JobeetBundle\Entity\Post:
    type: entity
    table: post
    repositoryClass: My\JobeetBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:

        FirstName:
            type: string
            length: 255
        LasttName:
            type: string
            length: 255
        email:
            type: string
            length: 255

    oneToOne:
        cv:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            cascade: ["persist", "merge"]
            joinColumn:
                name: cv_id
                referencedColumnName: id
        LettreM:
                    targetEntity: Application\Sonata\MediaBundle\Entity\Media
                    cascade: ["persist", "merge"]
                    joinColumn:
                        name: Lettre_id
                        referencedColumnName: id
    lifecycleCallbacks: {  }
