job:
    path:     /{category}
    defaults: { _controller: "MyJobeetBundle:Job:index",category: null  }
job_show:
    path:     /{id}/show
    defaults: { _controller: "MyJobeetBundle:Job:show" }

post_post:
    path:     /job/post
    defaults: { _controller: "MyJobeetBundle:Post:post" }

post_success:
    path:     /post/success
    defaults: { _controller: "MyJobeetBundle:Post:success" }
