job:
    path:     /
    defaults: { _controller: "MyJobeetBundle:Job:index" }
job_show:
    path:     /{id}/show
    defaults: { _controller: "MyJobeetBundle:Job:show" }
cat_show:
    path:     /categorie/{id}
    defaults: { _controller: "MyJobeetBundle:Job:liste" }
