job:
    path:     /{category}
    defaults: { _controller: "MyJobeetBundle:Job:index",category: null  }
job_show:
    path:     /{id}/show
    defaults: { _controller: "MyJobeetBundle:Job:show" }
job_post:
    path:     /post
    defaults: { _controller: "MyJobeetBundle:Post:post" }

post_success:
    path:     /success
    defaults: { _controller: "MyJobeetBundle:Job:sucess" }
