job:
    path:     /{category}
    defaults: { _controller: "MyJobeetBundle:Job:index",category: null  }
job_show:
    path:     /{id}/show
    defaults: { _controller: "MyJobeetBundle:Job:show" }
job_postule:
    path:     /{email}/postule
    defaults: { _controller: "MyJobeetBundle:Job:postule" }
    requirements: { _method: post }
postule_success:
    path:     /success
    defaults: { _controller: "MyJobeetBundle:Job:sucess" }
